from sys import argv
script,filename=argv
print("we are going to erase %r." % filename)
print("if you don't want that ,hit CTR-C (^c).")
print("if you want , hit RETURN")
input("?")
print("opening the file...")
target=open(filename,"w")
print("Truncating the file.Goodbye")
target.truncate()
print("Now,i'm telling you for three lines.")
line1=input("line1:")
line2=input("line2:")
line3=input("line3:")
print("I'm going to write this to the file.")
target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")

print("And finally,we close it")
target.close()